export enum ApiRoutes {
    USERS = "/users/getAll",
    ADD_USER = "/auth/add-user",
    REGISTER = "/auth/register",
    CREATE_FOLDER = "/folder/create",
    CREATE_FILE = "/files/upload",
    GET_FILE = "/files/",
    PREVIEW_FILE = "/files/view/",
    USER_DISK = "/user-disk/get",
    SEND_CODE = "/auth/send-code",
    VERIFY_CODE = "/auth/verify-user",
    DELETE_FILE = "/files/delete/",
    DOWNLOAD_SELECTED_FILES = "/files/download-selected",
    ADD_COMMENT = "/users/add-comment",
}
