import { AdminHeader } from "@/components/shared/admin/admin-header";
import { SideBar } from "@/components/shared/side-bar";
import { authOptions } from "@/constants/auth-options";
import { getServerSession } from "next-auth";

export const metadata = {
    title: "Users",
    description: "Generated by Next.js",
};

export default async function UsersLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const user = await getServerSession(authOptions);
    return (
        <div className="h-screen overflow-hidden flex flex-col">
            {user?.user.role === "ADMIN" && <AdminHeader />}
            <div className="flex flex-1 overflow-hidden">
                <SideBar className="basis-1/5 overflow-y-auto" />
                <main className="flex-1 overflow-y-auto flex flex-col bg-primary p-4">
                    {children}
                </main>
            </div>
        </div>
    );
}
